import numpy as np
import random


def map_number_to_card(number):
    """
    Map a number (0-415) to a card representation
    Format: {suit}{rank}{deck_num}
    suit: S, D, H, C
    rank: 2-10, J, Q, K, A
    deck_num: 1-8

    Args:
        number (int): Number from 0 to 415

    Returns:
        str: Card representation (e.g., "S21", "D103", "HA8")
    """
    if not 0 <= number <= 415:
        raise ValueError("Number must be between 0 and 415")

    # Calculate suit, rank, and deck number
    deck_num = (number // 52) + 1  # 1-8
    card_in_deck = number % 52

    suit_idx = card_in_deck // 13  # 0-3
    rank_idx = card_in_deck % 13  # 0-12

    # Map suit indices to suit symbols
    suits = ["S", "D", "H", "C"]  # Spades, Diamonds, Hearts, Clubs
    suit = suits[suit_idx]

    # Map rank indices to rank symbols
    ranks = ["2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"]
    rank = ranks[rank_idx]

    return f"{suit}{rank}{deck_num}"


def map_sequence_to_cards(sequence):
    """
    Convert a sequence of numbers to card representations

    Args:
        sequence (list): List of numbers from 0 to 415

    Returns:
        list: List of card representations
    """
    return [map_number_to_card(num) for num in sequence]


def calculate_correlation(s1, s2):
    """
    Calculate correlation between two sequences using the formula:
    Corr = (Σ_{i=1}^{N} I(S1_i = S2_i)) / N

    Where I is the indicator function: I(S1_i = S2_i) = 1 if S1_i = S2_i, 0 otherwise

    Args:
        s1 (list or array): First sequence
        s2 (list or array): Second sequence

    Returns:
        float: Correlation value between 0 and 1
    """
    if len(s1) != len(s2):
        raise ValueError("Sequences must have the same length")

    N = len(s1)
    if N == 0:
        return 0.0

    # Calculate sum of indicator functions
    sum_indicators = sum(1 for i in range(N) if s1[i] == s2[i])

    # Calculate correlation
    correlation = sum_indicators / N

    return correlation


def generate_random_sequence(length, num_values):
    """
    Generate a random sequence with specified length using sampling without replacement

    Args:
        length (int): Length of the sequence (must be <= num_values)
        num_values (int): Number of possible values to choose from

    Returns:
        list: Random sequence with unique values (sampling without replacement)
    """
    if length > num_values:
        raise ValueError(
            f"Length ({length}) cannot be greater than number of values ({num_values})"
        )

    # Create a list of all possible values and randomly sample without replacement
    all_values = list(range(num_values))
    return random.sample(all_values, length)


def test_correlation_calculation():
    """
    Test the correlation calculation with default parameters
    """
    print("Testing correlation calculation...")
    print("=" * 50)

    # Demo 1: Default parameters with sampling without replacement
    print(
        "Demo 1 - Default parameters (N=50, m=416) - Sampling without replacement:"
    )
    s1 = generate_random_sequence(50, 416)
    s2 = generate_random_sequence(50, 416)
    corr = calculate_correlation(s1, s2)
    print(f"Random S1 (first 10 cards): {map_sequence_to_cards(s1[:10])}...")
    print(f"Random S2 (first 10 cards): {map_sequence_to_cards(s2[:10])}...")
    print(f"Correlation: {corr:.4f}")
    print(
        f"Note: Each sequence contains unique values from 0 to 415 (52 cards × 8 decks)"
    )
    print()

    # Demo 2: Sequence 2 is generated by swapping two sub-sequences of equal length from sequence 1
    print(
        "Demo 2 - Sequence 2 generated by swapping two sub-sequences from sequence 1:"
    )
    # Generate a new sequence for demo 2
    s1_demo2 = generate_random_sequence(50, 416)

    # Choose two sub-sequences of equal length (e.g., length 5)
    sub_length = 5
    start1 = 10  # First sub-sequence starts at position 10
    start2 = 25  # Second sub-sequence starts at position 25

    # Create sequence 2 by swapping the two sub-sequences
    s2_demo2 = s1_demo2.copy()
    (
        s2_demo2[start1 : start1 + sub_length],
        s2_demo2[start2 : start2 + sub_length],
    ) = (
        s2_demo2[start2 : start2 + sub_length],
        s1_demo2[start1 : start1 + sub_length],
    )

    corr_demo2 = calculate_correlation(s1_demo2, s2_demo2)
    print(
        f"Original S1 (first 15 cards): {map_sequence_to_cards(s1_demo2[:15])}..."
    )
    print(
        f"Modified S2 (first 15 cards): {map_sequence_to_cards(s2_demo2[:15])}..."
    )
    print(
        f"Sub-sequence 1 (positions {start1}-{start1+sub_length-1}): {map_sequence_to_cards(s1_demo2[start1:start1+sub_length])}"
    )
    print(
        f"Sub-sequence 2 (positions {start2}-{start2+sub_length-1}): {map_sequence_to_cards(s1_demo2[start2:start2+sub_length])}"
    )
    print(f"Correlation after swapping: {corr_demo2:.4f}")
    print(f"Note: S2 is S1 with two {sub_length}-length sub-sequences swapped")
    print()


def main():
    """
    Main function to demonstrate the correlation calculation
    """
    print("Sequence Correlation Calculator")
    print("=" * 50)
    print("Formula: Corr = (Σ_{i=1}^{N} I(S1_i = S2_i)) / N")
    print("Where I is the indicator function")
    print("Sequences are generated using sampling without replacement")
    print("Card mapping: {suit}{rank}{deck_num}")
    print(
        "Example: S21 (Spades Ace from deck 1), D103 (Diamonds 10 from deck 3)"
    )
    print()

    # Run tests
    test_correlation_calculation()

    # Interactive example
    print("Interactive Example:")
    print("Enter two sequences to calculate correlation")
    print("Enter 'q' to quit")
    print()

    while True:
        try:
            # Get sequence 1
            s1_input = input(
                "Enter first sequence (space-separated numbers, or 'q' to quit): "
            )
            if s1_input.lower() == "q":
                break

            s1 = [int(x) for x in s1_input.split()]

            # Get sequence 2
            s2_input = input(
                "Enter second sequence (space-separated numbers): "
            )
            s2 = [int(x) for x in s2_input.split()]

            # Calculate and display correlation
            corr = calculate_correlation(s1, s2)
            print(f"Correlation: {corr:.4f}")
            print(f"S1 (cards): {map_sequence_to_cards(s1)}")
            print(f"S2 (cards): {map_sequence_to_cards(s2)}")
            print()

        except ValueError as e:
            print(f"Error: {e}")
            print("Please enter valid numbers separated by spaces")
            print()
        except KeyboardInterrupt:
            print("\nGoodbye!")
            break


if __name__ == "__main__":
    main()
